module.exports = {
  "configs": {
    "typescript": {
      "plugins": [
        "@typescript-eslint",
        "import",
      ],
      "extends": [
        "eslint:recommended",
        "plugin:@typescript-eslint/recommended",
        "plugin:@typescript-eslint/recommended-requiring-type-checking",
        "plugin:import/errors",
        "plugin:import/warnings",
        "plugin:import/recommended",
        "plugin:import/typescript",
        "prettier",
      ],
      "rules": {
        "array-callback-return": "error",
        "@typescript-eslint/array-type": "error",
        "@typescript-eslint/ban-ts-comment": "off",
        "consistent-return": "warn",
        "@typescript-eslint/consistent-type-assertions": "warn",
        "@typescript-eslint/consistent-type-definitions": ["error", "interface"],
        "@typescript-eslint/consistent-type-imports": "warn",
        "@typescript-eslint/explicit-function-return-type": "off",
        "import/extensions": ["warn", "never"],
        "import/first": "warn",
        "linebreak-style": "warn",
        "max-len": ["warn", 100],
        "import/newline-after-import": "warn",
        "no-constructor-return": "error",
        "@typescript-eslint/no-dupe-class-members": "warn",
        "no-duplicate-imports": "off",
        "@typescript-eslint/no-duplicate-imports": "warn",
        "@typescript-eslint/no-explicit-any": "off",
        "no-fallthrough": "warn",
        "no-lone-blocks": "warn",
        "no-lonely-if": "warn",
        "no-multiple-empty-lines": ["warn", {
          "max": 1,
          "maxBOF": 0,
          "maxEOF": 0,
        }],
        "no-nested-ternary": "warn",
        "no-new-wrappers": "error",
        "@typescript-eslint/no-non-null-assertion": "off",
        "no-throw-literal": "error",
        "@typescript-eslint/no-unnecessary-condition": "error",
        "@typescript-eslint/no-unnecessary-type-constraint": "warn",
        "@typescript-eslint/no-unsafe-assignment": "off",
        "@typescript-eslint/no-unsafe-call": "off",
        "@typescript-eslint/no-unsafe-member-access": "off",
        "@typescript-eslint/no-unused-expressions": "warn",
        "@typescript-eslint/no-unused-return": "off",
        "@typescript-eslint/no-unused-vars": ["warn", {
          "args": "after-used",
          "argsIgnorePattern": "^_",
          "ignoreRestSiblings": true,
          "caughtErrors": "none",
        }],
        "@typescript-eslint/no-use-before-define": "off",
        "import/no-useless-path-segments": ["error", {
          "noUselessIndex": true,
        }],
        "no-whitespace-before-property": "warn",
        "operator-assignment": "warn",
        "import/order": ["warn", {
          "groups": [
            "builtin",
            "external",
            "internal",
            "unknown",
            ["parent", "sibling", "index"],
          ],
          "newlines-between": "always",
          "alphabetize": {
            "order": "asc",
            "caseInsensitive": true,
          }
        }],
        "prefer-const": "off",
        "@typescript-eslint/prefer-nullish-coalescing": "warn",
        "@typescript-eslint/prefer-optional-chain": "warn",
        "prefer-rest-params": "warn",
        "prefer-spread": "warn",
        "require-atomic-updates": "off",
        "@typescript-eslint/require-await": "off",
        "rest-spread-spacing": "warn",
        "@typescript-eslint/restrict-template-expressions": "off",
        "spaced-comment": ["warn", "always", {
          "block": {
            "balanced": true,
          },
        }],
        "@typescript-eslint/unbound-method": "off",
      },
      "overrides": [{
        // enable these rules specifically for TypeScript files
        "files": ["*.ts", "*.tsx"],
        "rules": {
          "consistent-return": "off",
          "import/default": "off",
          "@typescript-eslint/explicit-function-return-type": ["warn", {
            "allowExpressions": true,
            "allowTypedFunctionExpressions": true,
            "allowHigherOrderFunctions": true,
            "allowConciseArrowFunctionExpressionsStartingWithVoid": true,
          }],
          "@typescript-eslint/explicit-member-accessibility": "warn",
          "@typescript-eslint/explicit-module-boundary-types": "off",
          "import/named": "off",
          "import/namespace": "off",
          "@typescript-eslint/no-empty-interface": "off",
          "@typescript-eslint/no-inferrable-types": ["warn", {
            "ignoreParameters": true,
          }],
          "import/no-named-as-default-member": "off",
          "import/no-unresolved": "off",
          "@typescript-eslint/no-unnecessary-type-arguments": "warn",
          "@typescript-eslint/typedef": ["warn", {
            "arrayDestructuring": false,
            "arrowParameter": true,
            "memberVariableDeclaration": false,
            "objectDestructuring": false,
            "parameter": true,
            "propertyDeclaration": true,
            "variableDeclaration": false,
            "variableDeclarationIgnoreFunction": true,
          }],
        },
        "settings": {
          "import/resolver": {
            "typescript": {
              "alwaysTryTypes": true,
            },
          },
        },
      }, {
        // enable these rules specifically for JavaScript files
        "files": ["*.js", "*.jsx"],
        "rules": {
          "@typescript-eslint/no-var-requires": "off",
        }
      }, {
        "files": [
          "**/*.test.js",
          "**/*.test.jsx",
          "**/*.test.ts",
          "**/*.test.tsx",
          "**/__mocks__/*.js",
          "**/__mocks__/*.ts",
        ],
        "env": {
          "jest": true,
        },
      }]
    },
    "react": {
      "plugins": [
        "react",
        "react-hooks",
      ],
      "extends": [
        "plugin:react/recommended",
        "plugin:react-hooks/recommended",
      ],
      "rules": {
        "react/button-has-type": "warn",
        "react/jsx-boolean-value": ["warn", "always"],
        "react/jsx-curly-brace-presence": ["warn", "never"],
        "react/jsx-filename-extension": ["warn", {
          "extensions": [".tsx", ".jsx"],
        }],
        "react/jsx-fragments": ["warn", "syntax"],
        "react/jsx-no-bind": "warn",
        "react/jsx-no-useless-fragment": "warn",
        "react/jsx-pascal-case": "warn",
        "react/no-access-state-in-setstate": "warn",
        "react/no-array-index-key": "warn",
        "react/no-danger": "warn",
        "react/no-did-mount-set-state": "warn",
        "react/no-did-update-set-state": "warn",
        "react/no-redundant-should-component-update": "warn",
        "react/no-this-in-sfc": "error",
        "react/no-typos": "error",
        "react/no-unsafe": "warn",
        "react/no-unused-state": "warn",
        "react/no-will-update-set-state": "error",
        "react/prefer-es6-class": "error",
        "react/prop-types": "off",
        "react/react-in-jsx-scope": "off",
        "react/require-optimization": "warn",
        "react/self-closing-comp": "warn",
        "react/style-prop-object": "error",
        "react/void-dom-elements-no-children": "error",
      },
    },
  },
};
